# Generated by Django 2.1.3 on 2019-05-15 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.CharField(blank=True, default='', max_length=50)),
                ('address', models.CharField(blank=True, default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_date', models.DateField(default=django.utils.timezone.now)),
                ('delivery_date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('status', models.CharField(choices=[('S', 'at thе sender'), ('P', 'at the post'), ('R', 'at the recipient')], default='S', max_length=30)),
                ('type', models.CharField(choices=[('C', 'common'), ('E', 'express')], default='C', max_length=30)),
                ('size', models.CharField(choices=[('S', 'small box'), ('M', 'medium box'), ('L', 'large box'), ('XL', 'extra large box'), ('WP', 'wrapped parcel'), ('DOC', 'documents')], max_length=5)),
                ('from_address', models.CharField(max_length=150)),
                ('from_phone', models.CharField(max_length=11)),
                ('to_address', models.CharField(max_length=150)),
                ('to_phone', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, default='', max_length=9)),
                ('type', models.CharField(choices=[('WH', 'warehouse'), ('MO', 'main office')], default='WH', max_length=50)),
                ('total_space', models.CharField(blank=True, default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, default='', max_length=150)),
                ('pk_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_type', models.CharField(choices=[('C', 'common'), ('E', 'express')], default='C', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=50)),
                ('capacity', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('mid_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone', models.CharField(blank=True, default='', max_length=9)),
                ('email', models.CharField(blank=True, default='', max_length=50)),
                ('address', models.CharField(blank=True, default='', max_length=150)),
                ('position', models.CharField(blank=True, default='', max_length=50)),
                ('pk_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.Post')),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='pk_courier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.Worker'),
        ),
        migrations.AddField(
            model_name='trip',
            name='pk_vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.Vehicle'),
        ),
        migrations.AddField(
            model_name='package',
            name='pk_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.Post'),
        ),
        migrations.AddField(
            model_name='package',
            name='pk_trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.Trip'),
        ),
        migrations.AddField(
            model_name='package',
            name='pk_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.Profile'),
        ),
    ]
